"""user phone_number

Revision ID: 1314bfcbd0f2
Revises: 50dfc7475fa3
Create Date: 2024-01-28 04:33:28.966074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1314bfcbd0f2'
down_revision: Union[str, None] = '50dfc7475fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Application', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'User', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'phone_number')
    op.drop_column('Application', 'created_at')
    # ### end Alembic commands ###
