"""application

Revision ID: 50dfc7475fa3
Revises: 6b89724ef45c
Create Date: 2024-01-28 04:08:46.604823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50dfc7475fa3'
down_revision: Union[str, None] = '6b89724ef45c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Application',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('insurance_sum', sa.BigInteger(), nullable=True),
    sa.Column('total_insurance_premium', sa.BigInteger(), nullable=True),
    sa.Column('main_coverage_premium', sa.BigInteger(), nullable=True),
    sa.Column('ns_premium', sa.BigInteger(), nullable=True),
    sa.Column('disability_premium', sa.BigInteger(), nullable=True),
    sa.Column('tt_premium', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Application')
    # ### end Alembic commands ###
